[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"

# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1YkL8ZwK3bCdwlywd9Dcd3F6o_tW4xqMOyuflgEAu2iY"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "entry-form-415619"
private_key_id = "f4d0010227cd8eca18cd89827ffbdf4ef8c6a15a"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCO0NVF/q99S8az\nSxSXpVicOnf3gf4k+Ekj8QJxPXPKgh2Ll67iUPrMjYHubfb1JKtMwyctjhXvoyqW\nRWuDxlfQTmBZOmoMK1f7XojOSrVAXzLDmp5PB6AluWNPgzGBgBoJir6eBuod6Gdq\n5hXRoKewbEdnMDXKv8xzE609cZWcZ5rLk77Y9g0t5MEssBu3Cz5Qkm1Oxqs0djWm\nSXwXiAW3yd5p2Of7hOOer8a1AkugzLrXnwr5/B2r8SBTBX/XwnNWwJSxzxpJpetF\nkzBSbZrfna9wquVBQV1GGXK2ppEZFodWbop0de1QIgHjQ9NbdlQup/hyhKmeRHU8\nDKLo86BVAgMBAAECggEACw82y4A88Jfpt9CF3vYbM01KJSoqzIvx8AerH9VO2PJe\nstoTcoEBDE5IrvZ9iWomSMq+XIZUV7XGkmim+jH7HWK1uTCEmKjSRqFBY1uWMc6y\nye0jOsKqqcPeN1X/w1lF9ZIKD7HrNyyG4QNB0nVdiamM6vupAr3RFDfvHQ26yf0p\n+ogfcrMUhoz9+7b8VIF6tfa7qTwUN04Lu6k451MLJYLqpUiz9W1Sh9zX69WkctSv\n9c6JdK3WXtn8J+fq53v6M/QLjZPNu1LM2MxvCHwN4Pctzgxvf4ecsL9LqbVMW2hp\nlgn75/WBx90CYsJZnTrWSVDql8Hi+ZIDxl1hg73mcQKBgQC/17nIfsXKGkmOTV1R\nmEgb7+AGCGior2/vzIsgvWe4jB+Y7hEHNFXtSViHhgwe8yo6kfiVNaZA7mlugku+\nJ3W8n6j+1YuCTa4nAzxTtmLUdiKXJDPpf/Wl88XIuvwTM/RbcxkOHn17mDlQicpz\noLxS/nT4fmQCd/qdMG/N3iSHBQKBgQC+k8DXzBt6DFITjLrDDNxNdnP7n64vv0j2\n4GZpR74XYRbHKT9kwApBPEGWpEziMEliRYyrsAAsu4/KTWHXNRU9EF8MrQCerre7\n3051fgl4blzJTXlfdNpcU4AUNv8rOvot4gkjthBMwkxQBiCBO1hIt2mr50Yu3PZd\nevX5c4pVEQKBgDCEIAnidabc6wk/63+9IU9fZKph6gXvCEH+2piXDeoQFdWZL1lB\nFRIDYI41ik8xc9aIH/OsM7VsFeHKtdkLJa1kO1rnKnbzqj1XhiQtleThU3Ihx7cf\nk0I62iQflaxNkVinTQjTESz2nFgP4NFJLxdWHsLRQ/2T1h92pm/L5DT5AoGBAJwE\nMdd4jPX5qCfBChQsLx5rXsAcFWmZW45gXvbJeOGC5jbdmbxNSxfk0H0WvKpfhXQi\nI+taBoqYcjrX5sVb+6sl/+pMpzlBJ8FyKrUdHXuuPd++wSJYc3sqEKx76aHmgnGV\nno3Rur5cQkUw/uNNRhUhsiy9BUPQORCGXWB+Kj1BAoGAVa0n0VuwV8f2Sy/Iy6T9\nw4YV+6sWneglnkjuwsg7U19W5r1wgCszBajq53IvwUXI3OFU6jUeNwIhtJGnhnMa\nB7ENkcns0/oJBEc1J1i1tx5halFrBSyOupemodKDhOtOqm8hwKU1dCTTBhzq1Amg\ngFjqkQB+QXk40U5VM/FCNGw=\n-----END PRIVATE KEY-----\n"
client_email = "google-sheets-python-access@entry-form-415619.iam.gserviceaccount.com"
client_id = "101333269640144346195"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/google-sheets-python-access%40entry-form-415619.iam.gserviceaccount.com"